export type Product = {
    id: number
    title: string
    type: string
    text?: string
    price: number
    category: string
}

const productsArray: Product[] = [
    {
        id: 1,
        title: './images/o_1.jpg',
        type: 'Обруч',
        text: 'Материал: атлас',
        price: 20,
        category: 'обруч',
    },
    {
        id: 2,
        title: './images/o_2.jpg',
        type: 'Обруч',
        text: 'Материал: атлас',
        price: 30,
        category: 'обруч',
    },
    {
        id: 3,
        title: './images/o_3.jpg',
        type: 'Обруч',
        text: 'Материал: атлас',
        price: 50,
        category: 'обруч',
    },
    {
        id: 4,
        title: './images/p_1.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 5,
        title: './images/p_2.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 6,
        title: './images/p_3.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 7,
        title: './images/p_4.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 8,
        title: './images/p_5.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 9,
        title: './images/p_6.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 10,
        title: './images/p_7.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 11,
        title: './images/p_8.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 12,
        title: './images/p_9.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 13,
        title: './images/p_10.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 14,
        title: './images/p_11.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 15,
        title: './images/p_12.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 16,
        title: './images/p_13.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 17,
        title: './images/p_14.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 18,
        title: './images/p_15.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 19,
        title: './images/p_16.jpg',
        type: "Пов'язка",
        text: 'Материал: атлас',
        price: 20,
        category: "пов'язка",
    },
    {
        id: 20,
        title: './images/r_1.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 21,
        title: './images/r_2.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 22,
        title: './images/r_3.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 23,
        title: './images/r_4.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 24,
        title: './images/r_5.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 25,
        title: './images/r_6.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 26,
        title: './images/r_7.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 27,
        title: './images/r_8.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 28,
        title: './images/r_9.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 29,
        title: './images/r_10.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 30,
        title: './images/r_11.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 31,
        title: './images/r_12.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 32,
        title: './images/r_13.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 33,
        title: './images/r_14.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 34,
        title: './images/r_15.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 35,
        title: './images/r_16.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 36,
        title: './images/r_17.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 37,
        title: './images/r_18.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 38,
        title: './images/r_19.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 39,
        title: './images/r_20.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 40,
        title: './images/r_21.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 41,
        title: './images/r_22.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 42,
        title: './images/r_23.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 43,
        title: './images/r_24.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 44,
        title: './images/r_25.jpg',
        type: 'Резинка',
        text: 'Материал: атлас',
        price: 20,
        category: 'резинка',
    },
    {
        id: 45,
        title: './images/y_1.jpg',
        type: 'Уточка',
        text: 'Материал: атлас',
        price: 20,
        category: 'уточка',
    },
    {
        id: 46,
        title: './images/y_2.jpg',
        type: 'Уточка',
        text: 'Материал: атлас',
        price: 20,
        category: 'уточка',
    },
    {
        id: 47,
        title: './images/y_3.jpg',
        type: 'Уточка',
        text: 'Материал: атлас',
        price: 20,
        category: 'уточка',
    },
]

export const getProductsObject = (array: Product[]) =>
    array.reduce(
        (object, product) => ({
            ...object,
            [product.id]: product,
        }),
        {}
    )

export default productsArray
